- hosts: all
  gather_facts: yes
  pre_tasks:
    - name: Set Elasticsearch host variable
      set_fact:
        elasticsearch_host: "{{ hostvars['master1']['ansible_host'] }}"

- name: Install Elasticsearch on all nodes
  hosts: elk
  roles:
    - elasticsearch

- name: Install Kibana on master1
  hosts: master1
  roles:
    - kibana

- name: Install Logstash (optional, choose a node)
  hosts: data1
  vars:
    elasticsearch_user: "elastic"
    elasticsearch_password: "temp123!@#"
  roles:
    - logstash
