---
- name: Import Kibana GPG Key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Kibana Repository
  ansible.builtin.apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
    state: present
    update_cache: yes
  become: yes

- name: Install Kibana
  ansible.builtin.apt:
    name: kibana
    state: latest
  become: yes

- name: Configure Kibana
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0644
  # notify:
  #   - restart kibana
  become: yes

- name: Enable and Start Kibana Service
  ansible.builtin.service:
    name: kibana
    enabled: yes
    state: started
  become: yes

